# Generated by scripts/update-gag.sh from the v0.6.0 release. Do not edit.
cask "gag" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_amd64.tar.gz"
      sha256 "375e7bcce0d7573a38980e3faa6ee3a30ac058ebea64b72d70ab640bfd32eb34"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_arm64.tar.gz"
      sha256 "5071694d78c3f5e777723dcf011e03b3744bebcc2ec63c90fc6e84dba55baf20"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_amd64.tar.gz"
      sha256 "c07ea7c416250a2c06b7a48eda778ed94b687a43ea221ecd516f2273a3a49bd6"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_arm64.tar.gz"
      sha256 "40464c3f54e091399d753584883a67dbc206309dcbf8365de197fc7ac2065910"
    end
  end

  name "gag"
  desc "Terminal garden of your git projects"
  homepage "https://github.com/RursusAeternum/GitAGarden"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "gag"

  # The binary isn't notarized; without this macOS refuses to run it.
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gag"],
                            writable_paths: ["gag"]
    end
  end
end
