# Generated by scripts/update-gag.sh from the v0.1.2 release. Do not edit.
cask "gag" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_amd64.tar.gz"
      sha256 "12cee85fb6fb80dcdcfa900e0574fde640c2c9419ac6f1494ef733cb7bff59be"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_arm64.tar.gz"
      sha256 "3e72053a71124961ca7c44a33fb796e4d5214e8c77e32176e62a2bb6186edebd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_amd64.tar.gz"
      sha256 "e144665db5e3f7dce28bd337e2b1de5b370af72326c182d99165edebf05e108a"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_arm64.tar.gz"
      sha256 "f9c8941e4b9ec10e1ff6edc9672c1ec8bb87b7c8a3e101c197b112fc98f23d5c"
    end
  end

  name "gag"
  desc "Terminal garden of your git projects"
  homepage "https://github.com/RursusAeternum/GitAGarden"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "gag"

  # The binary isn't notarized; without this macOS refuses to run it.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gag"]
    end
  end
end
