# Generated by scripts/update-gag.sh from the v0.8.0 release. Do not edit.
cask "gag" do
  version "0.8.0"

  on_macos do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_amd64.tar.gz"
      sha256 "1828f1509af713036bb7468120baf1517266ade6cf1346ee40cb82d61a0998d6"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_darwin_arm64.tar.gz"
      sha256 "17d7d0c77c079d982d1c61e24f10f46aa1424350065cb7bfdf190d207b85722e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_amd64.tar.gz"
      sha256 "35a63cba2b7c6ed3a82aea33f2098794600515ea9de34399e548fbc960716af4"
    end
    on_arm do
      url "https://github.com/RursusAeternum/GitAGarden/releases/download/v#{version}/gag_linux_arm64.tar.gz"
      sha256 "d4f270a0149c1a02d887870957254b3f62bc1745eb510905bcb4846a6fb66650"
    end
  end

  name "gag"
  desc "Terminal garden of your git projects"
  homepage "https://github.com/RursusAeternum/GitAGarden"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "gag"

  # The binary isn't notarized; without this macOS refuses to run it.
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gag"],
                            writable_paths: ["gag"]
    end
  end
end
