#!/bin/sh
# Regenerate Casks/gag.rb from the latest RursusAeternum/GitAGarden release.
# Needs gh (authenticated; any token that can read public releases works).
set -eu

repo=RursusAeternum/GitAGarden
tag=$(gh release view --repo "$repo" --json tagName --jq .tagName)
version=${tag#v}
sums=$(gh release download "$tag" --repo "$repo" --pattern checksums.txt --output -)

sha() {
  s=$(printf '%s\n' "$sums" | awk -v f="gag_$1.tar.gz" '$2 == f { print $1 }')
  [ -n "$s" ] || { echo "no checksum for gag_$1.tar.gz in $tag" >&2; exit 1; }
  printf '%s' "$s"
}

darwin_amd64=$(sha darwin_amd64)
darwin_arm64=$(sha darwin_arm64)
linux_amd64=$(sha linux_amd64)
linux_arm64=$(sha linux_arm64)

url="https://github.com/$repo/releases/download/v#{version}"

mkdir -p Casks
cat > Casks/gag.rb <<EOF
# Generated by scripts/update-gag.sh from the $tag release. Do not edit.
cask "gag" do
  version "$version"

  on_macos do
    on_intel do
      url "$url/gag_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
    on_arm do
      url "$url/gag_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
  end

  on_linux do
    on_intel do
      url "$url/gag_linux_amd64.tar.gz"
      sha256 "$linux_amd64"
    end
    on_arm do
      url "$url/gag_linux_arm64.tar.gz"
      sha256 "$linux_arm64"
    end
  end

  name "gag"
  desc "Terminal garden of your git projects"
  homepage "https://github.com/$repo"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "gag"

  # The binary isn't notarized; without this macOS refuses to run it.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gag"]
    end
  end
end
EOF
echo "Casks/gag.rb -> $version"
